### ISSUE TITLE
How to get 'lidar_coord'?

### ISSUE THREAD

**Issue by Zehaos** [jeasinema/tf_voxelnet#16]
Hi, @jeasinema 

Could you kindly shed more light on "lidar_coord"? 
How to get the coordinate of the lidar? Is it necessary to shift the point cloud by adding "lidar_coord"?

**Comment by jeasinema** [comment]
Hi,
I use `lidar` or `camera` for coordinate param in some functions located in `utils/utils.py` just because there are 3 coordinate systems in KITTI dataset, and I use 2 of them. All the lidar points are under the `lidar` coordinate system, but all the labels are in `camera` coordinate system. So for this purpose I have to transform the coordinate between them.

**Comment by Zehaos** [comment]
Sorry for my unclear question. 

I mean that why we need to shift the point cloud [here](https://github.com/jeasinema/tf_voxelnet/blob/master/utils/preprocess.py#L38)? To my knowledge, to transform the camera label to lidar coordinate, we only need  to use calibration matrix. 

Another question, is it suitable to use the mean calibration matrix from training set ([related code](https://github.com/jeasinema/tf_voxelnet/blob/master/config.py#L118-L138))?

**Comment by jeasinema** [comment]
Hi,
I think you need to check the 3.1 of the [paper](http://arxiv.org/abs/1711.06396). We add the bias only for a nonnegative coordinate, since then the coordinate is used for creating the voxel block.

**Comment by Zehaos** [comment]
Got it, thank you for your patience.

**Comment by luckysouthchou** [comment]
good job！
